root_path = "root_path"
checkpoint_path = "checkpoint_path"
pipeline_type = "pipeline_type"
model_name = "model_name"
year_month = "year_month"
country = "country"
org = "org"
app_env = "app_env"
version = "version"

# demo
demo_raw_path = "demo_raw_path"
demo_raw_from_db = "demo_raw_from_db"
demo_raw_parquet_path = "demo_raw_parquet_path"
titanic_data_path = "titanic_data_path"
pysparkml_model_path = "pysparkml_model_path"
